# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a63f1396ff47457262295d447c9304928f68d27cd1fb6a822579a67d56b480c15f257fab27d3fc14cef6c2576594e93303e0d55ab5550374c077558da1a21d

test:
  secret_key_base: eb409893882c2c6bd8473df13b6b07e7bf7571584c2c218cac72a87a7e4852d2211c5348b7e2af619ea39652a0e950d945f08b47f38e315c5d96781cd917d697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
